// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Custom API Routes
 *
 * This file is the editable surface for custom backend logic that
 * doesn't fit the auto-generated CRUD model (per-model GET/POST/PATCH/
 * DELETE under `/api/<model>s`). Anything you mount on the exported
 * Hono app shows up at `/api/...` alongside the generated CRUD routes.
 *
 * Examples:
 *   - Aggregations / dashboards: `app.get('/dashboard', ...)`
 *   - Webhooks: `app.post('/webhooks/stripe', ...)`
 *   - Auth flows: `app.post('/auth/login', ...)`
 *
 * For installed integrations (Jira, Slack, Google, Meta Ads, etc.):
 *
 * - Dashboards / list views / "my X" pages → mount a route HERE that
 *   uses `getServerToolsClient()`. Resolve identity per request with
 *   `<TOOLKIT>_GET_CURRENT_USER`, compose the calls you need, return
 *   a clean shape your component owns.
 *
 *   The SDK auto-parses tool result `data` on success (the runtime
 *   JSON.stringifies tool responses; @shogo-ai/sdk/tools >=1.3 parses
 *   them back). Index `data` like a plain object — do NOT write a
 *   `JSON.parse(result.data)` helper. Pass a generic to `execute<T>()`
 *   for typed access.
 *
 *   import { getServerToolsClient } from '@shogo-ai/sdk/tools'
 *
 *   app.get('/jira/my-issues', async (c) => {
 *     const tools = getServerToolsClient()
 *     const me = await tools.execute<{ accountId: string }>('JIRA_GET_CURRENT_USER', {})
 *     if (!me.ok || !me.data?.accountId) {
 *       return c.json({ error: me.error ?? 'not authenticated' }, 401)
 *     }
 *     const issues = await tools.execute<{ issues: unknown[] }>('JIRA_SEARCH_ISSUES', {
 *       jql: `assignee = "${me.data.accountId}"`,
 *     })
 *     if (!issues.ok) return c.json({ error: issues.error ?? 'search failed' }, 502)
 *     return c.json({ issues: issues.data?.issues ?? [] })
 *   })
 *
 *   In the browser, surface the server's `error` field — never throw
 *   `new Error('Failed to load X')`:
 *
 *     const res = await fetch('/api/jira/my-issues')
 *     const body = await res.json().catch(() => ({}))
 *     if (!res.ok) setError(body.error ?? `HTTP ${res.status}`)
 *     else setIssues(body.issues ?? [])
 *
 *   After writing or editing a route, hit it to confirm shape + status:
 *     curl -s -w "\nHTTP %{http_code}\n" http://localhost:$RUNTIME_PORT/api/jira/my-issues
 *   A green build proves the file compiled, not that the endpoint works.
 *
 * - Ad-hoc interactive actions (button clicks, form submits) → use
 *   `useTools()` directly in the component. Don't add a route here for
 *   single-call passthroughs.
 *
 * Hand-rolling a `fetch()` to the provider's REST API will fail
 * because the pod has no provider tokens — auth lives in the runtime.
 * NEVER hardcode the agent operator's identity (accountId, member id,
 * userId) into route code; resolve it per request as shown above.
 *
 * The runtime watches this file. Saving triggers a fast restart of
 * `server.tsx` (no schema regeneration, no `prisma db push`) so changes
 * land in under a second.
 *
 * The Prisma client is available — import it from `./src/lib/db`:
 *
 *   import { prisma } from './src/lib/db'
 *
 *   app.get('/stats', async (c) => {
 *     const userCount = await prisma.user.count()
 *     return c.json({ userCount })
 *   })
 *
 * Do NOT edit `server.tsx` — it is auto-generated by the SDK from
 * `shogo.config.json` and will be overwritten on the next regeneration.
 */

import { Hono } from 'hono'

const app = new Hono()

// Add your custom routes here. They mount under `/api/`.
// Example:
//   app.get('/hello', (c) => c.json({ message: 'Hello!' }))

export default app
